### ISSUE TITLE
Meta: common/security-features

### ISSUE THREAD

**Issue by hiroshige-g** [web-platform-tests/wpt#21815]
This is a (not-well-structured) dashboard to track issues around `common/security-features` generator, including the tests generated by the generator.
Feel free to add comments if you find something related to `common/security-features`.

- [ ] https://github.com/web-platform-tests/wpt/issues/21710
- [ ] `<link>` elements support `referrerpolicy` attributes (i.e. `"attr"` policy delivery), but aren't tested at all in `referrer-policy/gen` tests.
- [ ] Code health
    - [ ] https://github.com/web-platform-tests/wpt/issues/21708
    - [ ] https://github.com/web-platform-tests/wpt/issues/21709
