### ISSUE TITLE
Add tests to account for resource-timing/fetch integration changes

### ISSUE THREAD

**Issue by noamr** [web-platform-tests/wpt#28658]
During the integration of FETCH/ResourceTiming, some subtle changes were made.
WPT needs to account for them.

- [x] `fetchStart` and `startTime` when TAO-protected should not expose redirect time
- [x] `transferSize` is always `encodedBodySize + 300` or `0` (if cached). It shouldn't expose actual cookie value.
- [x] `nextHopProtocol` should be TAO protected: https://github.com/web-platform-tests/wpt/blob/master/resource-timing/nextHopProtocol-is-tao-protected.https.html
- [x]  Once the different initiator definition is done, the tests need to account for the details (see https://github.com/whatwg/html/issues/6542)
- [x] It's unclear whether service-workers/cached responses should carry forward some of the connection info. (https://github.com/whatwg/fetch/issues/1208) - tests exists, see https://wpt.live/service-workers/service-worker/resource-timing-fetch-variants.https.html
- [x] Once we reach consensus on network errors, add tests to account for specified behavior (https://github.com/whatwg/fetch/issues/1215)

**Comment by noamr** [comment]
@yoavweiss

**Comment by yoavweiss** [comment]
Would it make sense for this issue to sit in the resource timing repo?

**Comment by yoavweiss** [comment]
Transferring this to Resource Timing, so that the WebPerfWG won't lose track of this...

**Comment by yoavweiss** [comment]
The `transferSize` parts were covered as part of https://chromium-review.googlesource.com/c/chromium/src/+/2878693
