### ISSUE TITLE
Missing Regions tests

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#5556]
These have been moved over from bulk from csswg-test; each of these issues gives a summary of something that should be one or more test cases. However, due to the age of these issues, some of them may not describe behaviour that is still in the spec.

If you believe any of these issues needs discussion prior to working on it, please file a new issue here to discuss it. General discussion, however, can happen here.

If you write any tests for these, please link to this issue from the pull request and make sure someone marks it as done here.

 - [ ] [[css-regions-1] Style cascading when element is flowed in itself](https://github.com/w3c/csswg-test/issues/78)
 - [ ] [Proper parsing and rendering for flow-into and flow-from](https://github.com/w3c/csswg-test/issues/443)
 - [ ] [Parsing and rendering for `region-fragment`](https://github.com/w3c/csswg-test/issues/445)
 - [ ] [Parsing and rendering for the new fragmentation keywords (`region-avoid`,			`region-always`)](https://github.com/w3c/csswg-test/issues/446)
 - [ ] [Nested named flows and cycle detection](https://github.com/w3c/csswg-test/issues/447)
 - [ ] [Multi-column regions](https://github.com/w3c/csswg-test/issues/448)
 - [ ] [Regions' pseudo-elements](https://github.com/w3c/csswg-test/issues/449)
 - [ ] [Regions auto-sizing](https://github.com/w3c/csswg-test/issues/450)
 - [ ] [CSSOM - `NamedFlow` interface](https://github.com/w3c/csswg-test/issues/451)
 - [ ] [CSSOM - `Region` interface](https://github.com/w3c/csswg-test/issues/452)
 - [ ] [CSSOM - `regionoversetchange` event](https://github.com/w3c/csswg-test/issues/453)
 - [ ] [CSSOM - `regionfragmentchange` event](https://github.com/w3c/csswg-test/issues/454)
 - [ ] [DOM additions - `getClientRects()` and `getBoundingClientRects()`](https://github.com/w3c/csswg-test/issues/455)
 - [ ] [DOM additions - `offsetTop`, `offsetBottom`, `offsetLeft`, `offsetRight` and `offsetParent`](https://github.com/w3c/csswg-test/issues/456)
 - [ ] [CSS Regions and floats](https://github.com/w3c/csswg-test/issues/457)
 - [ ] [CSS Regions and positioned elements](https://github.com/w3c/csswg-test/issues/458)
 - [ ] [CSS Regions and CSS3 Sizing additions](https://github.com/w3c/csswg-test/issues/459)
 - [ ] [CSS Regions and Flexbox](https://github.com/w3c/csswg-test/issues/460)
 - [ ] [CSS Regions and Multicol](https://github.com/w3c/csswg-test/issues/461)
 - [ ] [CSS Regions and Shapes](https://github.com/w3c/csswg-test/issues/462)
 - [ ] [CSS Regions and Grid layout](https://github.com/w3c/csswg-test/issues/463)
 - [ ] [CSS Regions and list items](https://github.com/w3c/csswg-test/issues/464)
 - [ ] [CSS Regions and `&lt;iframe>`-s](https://github.com/w3c/csswg-test/issues/465)
 - [ ] [CSS Regions and `&lt;video>`](https://github.com/w3c/csswg-test/issues/466)
 - [ ] [CSS Regions and `&lt;canvas>`](https://github.com/w3c/csswg-test/issues/467)
 - [ ] [CSS Regions and `&lt;table>`](https://github.com/w3c/csswg-test/issues/468)
 - [ ] [CSS Regions and stacking contexts](https://github.com/w3c/csswg-test/issues/469)
 - [ ] [CSS Regions and fragmentation](https://github.com/w3c/csswg-test/issues/470)
 - [ ] [CSS Regions and dynamic content](https://github.com/w3c/csswg-test/issues/471)
 - [ ] [CSS Regions and interactive content](https://github.com/w3c/csswg-test/issues/472)
 - [ ] [User input events in CSS Regions](https://github.com/w3c/csswg-test/issues/473)
 - [ ] [User-action pseudo-classes](https://github.com/w3c/csswg-test/issues/474)
 - [ ] [CSS Regions and writing modes](https://github.com/w3c/csswg-test/issues/475)
 - [ ] [CSS Regions and transforms](https://github.com/w3c/csswg-test/issues/476)
 - [ ] [CSS Regions and animations/transitions](https://github.com/w3c/csswg-test/issues/477)
 - [ ] [CSS Regions and ShadowDOM](https://github.com/w3c/csswg-test/issues/478)
 - [ ] [Content clipping and overflowing](https://github.com/w3c/csswg-test/issues/479)
 - [ ] [Pseudo-elements and pseudo-classes in named flow contents](https://github.com/w3c/csswg-test/issues/480)

**Comment by stephenmcgruer** [comment]
Given we just did https://github.com/web-platform-tests/wpt/pull/21368, I assume this is no longer relevant @gsnedders ? (Or is it a different 'regions' concept?)
